name: Upload to S3

on: 
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: './build/'
          S3_ENDPOINT: 'payara-internal'
          S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
